### ISSUE TITLE
Vapor 3

### ISSUE THREAD

**Issue by mcdappdev** [nodes-vapor/flash#17]
Now that Vapor 3 is nearing a final release, what does the status look like for updating this library? I am **more than happy to write the Vapor 3 version** if someone can help point me in the right direction with `request.storage` not being around anymore.

**Comment by steffendsommer** [comment]
@mcdappdev thanks for following up on this. We have a meeting in 2 days where we will discus which packages to migrate and in which order. The progress for migrating to Vapor 3 can be followed here: https://github.com/nodes-vapor/readme/projects/2

I'm pretty confident that we will be migrating this package as we use it a lot (e.g. in our AdminPanel package), but on Thursday we should have a better overview. It would be great with some help on migrating the package. I'll make sure to let, whoever will be responsible for migrating this package, know that you're interested in helping 👍 

Let's keep this issue open for tracking the progress.

**Comment by mcdappdev** [comment]
Thank you!

**Comment by mcdappdev** [comment]
Wonderful! Thanks for the quick response to this. Let me know if you need an extra hand, but sounds like you have it under control :)

**Comment by steffendsommer** [comment]
First version to support Vapor 3 has been released https://github.com/nodes-vapor/flash/releases/tag/2.0.0-beta.1

2.0 milestone can be found here https://github.com/nodes-vapor/flash/milestone/1
