### ISSUE TITLE
Vapor 2

### ISSUE THREAD

**Issue by mcdappdev** [nodes-vapor/flash#5]
Now that Vapor 2 is released I'd love to see an official 1.0 tag supporting Vapor 2. 

This package is awesome! I use it in all my projects. Kudos.

**Comment by steffendsommer** [comment]
I'm glad to hear that @mcdappdev and I've already been looking into it. As soon as https://github.com/vapor/auth-provider gets the new tag, flash will be updated as well.

**Comment by mcdappdev** [comment]
Great!

**Comment by steffendsommer** [comment]
It's here @mcdappdev https://github.com/nodes-vapor/flash/releases/tag/1.0.0 :tada:

**Comment by mcdappdev** [comment]
Thanks you!! 👍
